services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./database/database.sqlite:/app/database/database.sqlite
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:lksdlkfksdfsdlkfklllkl
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite
    tty: true
